AutExerHome = "//a[contains(.,'Home')]"
AutExerSubsciptionText = "//h2[normalize-space()='Subscription']"
AutExerBelowArrow = "//i[@class='fa fa-angle-up']"
AutExerFullFledged = "//h2[contains(.,'Full-Fledged practice website for Automation Engineers')]"
addToCards="//a[@class='btn btn-default add-to-cart']"
continueShopping= "//button[@class='btn btn-success close-modal btn-block']"
goToCart="(//a[@href='/view_cart'])[1]"
ShoppingCart="//li[@class='active']"
