AutExerHome = "//a[contains(.,'Home')]"
AutExerSubsciptionText = "//h2[normalize-space()='Subscription']"
AutExerBelowArrow = "//i[@class='fa fa-angle-up']"
AutExerFullFledged = "//h2[contains(.,'Full-Fledged practice website for Automation Engineers')]"
addToCards="//a[@class='btn btn-default add-to-cart']"
continueShopping= "//button[@class='btn btn-success close-modal btn-block']"
goToCart="(//a[@href='/view_cart'])[1]"
ShoppingCart="//li[@class='active']"
ProceedToCheckout="//a[@class='btn btn-default check_out']"
RegisterLoginOnCheckoutPopup="(//a[@href='/login'])[2]"
RegisterLogin="//*[@href='/login']"
SignupEmailBox="//*[@data-qa='signup-email']"
SignupButton="//*[@data-qa='signup-button']"
idGender="id:uniform-id_gender2"
loginDirect="//a[@href='/login']"
CreateAccountButton="(//button[@type='submit'])[1]"
AccountCreatedText="//*[text()='Account Created!']"
viewCart="//*[@href='/view_cart'"
loggedInAsUsername="//li[10]//a[1]"
ContinueButton="//*[@data-qa='continue-button']"
AdvertismentScreen="//*[@id='dismiss-button']"

